apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctune-api
  labels:
    app: doctune
spec:
  # Otimização Profissional: Estratégia de Deploy (Rolling Update)
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: doctune
  template:
    metadata:
      labels:
        app: doctune
    spec:
      # Otimização Profissional: Graceful Shutdown (dá tempo para a API terminar as extrações em andamento)
      terminationGracePeriodSeconds: 60
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: doctune-container
        # Má prática na indústria: usar tag 'latest'. Agora usamos versionamento semântico.
        image: doctune-api:v1.0.0
        # Evita baixar imagens a cada restart do Pod (melhora a resiliência em caso de queda de rede)
        imagePullPolicy: IfNotPresent
        
        # Otimização Profissional: Segurança do Container
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false

        ports:
        - containerPort: 8000
        
        # Limites de Hardware mantidos
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "6Gi"
            cpu: "2"
          requests:
            nvidia.com/gpu: 1
            memory: "4Gi"
            cpu: "1"

        # Health Checks mantidos
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 40
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30

        # Variáveis de Ambiente
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
