apiVersion: v1
kind: Service
metadata:
  name: doctune-service
spec:
  selector:
    app: doctune
  ports:
    - protocol: TCP
      port: 80       # Porta externa
      targetPort: 8000 # Porta do container (FastAPI)
  type: LoadBalancer # Em K3s/Minikube local, isso expõe a porta via NodePort ou MetalLB
